name: Deploy-To-Firebase

on: 
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16.14
      uses: actions/setup-node@master
      with:
        node-version: 16.14    
    - name: Install dependencies
      run: npm install
    - name: Build
      run: hugo
    - uses: w9jds/firebase-action@master
      with:
        args: hugo && deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
